modLoader="javafml"
loaderVersion="${loader_version_range}"
license="BSD 3-Clause"

[[mods]]

modId="maid_restaurant"
version="0.2.6"
displayName="Maid Restaurant"
logoFile="logo.png"
authors="摸里傻"

description='''
An addon mod designed to deliver a restaurant-style automatic experience with maids.
'''

[[mixins]]
config="maid_restaurant.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies."maid_restaurant"]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies."maid_restaurant"]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies."maid_restaurant"]]
    modId="touhou_little_maid"
    type="required"
    versionRange="[1.5.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies."maid_restaurant"]]
    modId="kaleidoscope_cookery"
    type="required"
    versionRange="[1.1.2,)"
    ordering="NONE"
    side="BOTH"
